version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout:
            post: cp -r licenses/. $ANDROID_HOME/licenses
      - run: 
             name: build fix
             command: touch ~/.android/repositories.cfg
      - run: flutter doctor
      - run: flutter test 
      - run: flutter -v build apk --target lib/app/main.dart  
